# version: v0.0.1
[metadata]
  org = "anya.run"
  maintainer = "Anja Kammer"
  description = "Desired State File for an anya setup"

[settings]
  kubeContext = "$KUBE_CONTEXT"

[namespaces]
  [namespaces.anya]
  [namespaces.preview]
  [namespaces.production]
  [namespaces.kube-system]
    installTiller = true

[helmRepos]
  stable = "https://kubernetes-charts.storage.googleapis.com"
  brigade = "https://azure.github.io/brigade-charts"
  anya = "https://storage.googleapis.com/anya-deployment/charts"

[apps]

  [apps.brigade]
    namespace = "anya" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "brigade/brigade" # changing the chart name means delete and recreate this release
    version = "0.20.0" # chart version
    ### Optional values below
    valuesFile = "brigade-values.yaml" # leaving it empty uses the default chart values
    purge = true # will only be considered when there is a delete operation
    protected = false
    priority = -400

  [apps.brigade-github-app]
    namespace = "anya" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "brigade/brigade-github-app" # changing the chart name means delete and recreate this release
    version = "0.1.1" # chart version
    ### Optional values below
    valuesFile = "brigade-github-app-values.yaml" # leaving it empty uses the default chart values
    purge = true # will only be considered when there is a delete operation
    protected = false
    priority = -300

  [apps.nginx]
    namespace = "kube-system" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "stable/nginx-ingress" # changing the chart name means delete and recreate this release
    version = "0.29.1" # chart version
    ### Optional values below
    valuesFile = "nginx-values.yaml" # leaving it empty uses the default chart values
    purge = true # will only be considered when there is a delete operation
    protected = false
    priority = -200

  [apps.anya-app]
    namespace = "anya" # maps to the namespace as defined in namespaces above
    enabled = true # change to false if you want to delete this app release [default = false]
    chart = "anya/anya" # changing the chart name means delete and recreate this release
    version = "0.1.0" # chart version
    ### Optional values below
    valuesFile = "anya-values.yaml" # leaving it empty uses the default chart values
    purge = true # will only be considered when there is a delete operation
    protected = false
    priority = -100
