apiVersion: v1
kind: ConfigMap
metadata:
  name: anya-brigade-pipeline
  namespace: anya
  labels:
    app.kubernetes.io/managed-by: tiller
    app.kubernetes.io/instance: anya-brigade-pipeline
    # helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: anya-brigade-pipeline
data:
  # When the config map is mounted as a volume, these will be created as files.
  brigade.js: {{ .Files.Get "files/brigade.js" | quote}}
