{{- $fullName := include "anya.fullname" . -}}
{{- range .Values.projects }}
apiVersion: v1
kind: Secret
metadata:
  name: brigade-{{ sha256sum .project| trunc 54 }}
  namespace: anya
  labels:
    app: brigade
    chart: {{ $fullName }}
    release: {{ $fullName }}
    heritage: {{ $fullName }}
    component: project
  annotations:
    projectName: {{ .project | quote }}
type: "brigade.sh/project"
stringData:
  repository: {{ .repository | quote }}
  sharedSecret: {{ .sharedSecret | quote }}
  cloneURL: {{ .cloneURL | quote }}
  initGitSubmodules: {{ default "false" .initGitSubmodules | quote }}
  defaultScriptName: "anya-brigade-pipeline"
  defaultScript: ""
  vcsSidecar: "deis/git-sidecar:latest"
  vcsSidecarResources.limits.cpu: ""
  vcsSidecarResources.limits.memory: ""
  vcsSidecarResources.requests.cpu: ""
  vcsSidecarResources.requests.memory: ""
  {{ if .buildStorageSize }}
  buildStorageSize: {{ .buildStorageSize | quote }}
  {{- end }}
  {{ if .imagePullSecrets }}
  imagePullSecrets: {{ .imagePullSecrets | quote }}
  {{- end }}
  {{ if .secrets }}
  secrets: '{{ .secrets | toJson }}'
  {{- end }}
  {{ range $k, $v := .github}}
  github.{{ $k }}: {{ $v | quote }}
  {{- end }}
  {{ range $k, $v := .kubernetes }}
  kubernetes.{{ $k }}: {{ $v | quote }}
  {{- end }}
  {{ if .sshKey }}
  sshKey: {{.sshKey | replace "\n" "$" }}
  {{- end }}
  allowPrivilegedJobs: "true"
  allowHostMounts: "false"
  {{ range $k, $v := .worker -}}
  worker.{{ $k }}: {{ $v | quote }}
  {{ end -}}
  {{if .workerCommand -}}
  workerCommand: {{.workerCommand | quote }}
  {{- end }}
  {{if .genericGatewaySecret -}}
  genericGatewaySecret: {{ .genericGatewaySecret | quote }}
  {{- end }}
---
 {{- end }}
