kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: anya-deployer
 namespace: anya
subjects:
- kind: ServiceAccount
  name: anya-deployer
  namespace: anya
roleRef:
  kind: ClusterRole
  name: anya-deployer
  apiGroup: rbac.authorization.k8s.io
