# Default values for anya.
# This is a YAML-formatted file.

service:
  type: ClusterIP
  port: 80

ingress:
  host: anya.example.com

  ghAppServiceName: brigade-github-app-brigade-github-app
  ghAppServicePath: /events/github
  ghAppServicePort: 80

  tls:
      # TLS Certificate Secrets must be already created
      # for the namespaces: anya, production, preview.
    - secretName: anya-tls
      hosts:
      - anya.example.com

projects: []
  # - project: "GitHub-Account/my-app" # Name of the project, in the form "user/project"
  #   repository: "github.com/GitHub-Account/my-app" # Domain/Org/Project
  #   cloneURL: "https://github.com/GitHub-Account/my-app.git"
  #   sharedSecret: "superSecret" # Create this for the GitHub App
  #   github:
  #     token: "1234superSecret5678" # GitHub App > OAuth credentials > Client secret
  #   initGitSubmodules: "false"  # submodules should be checked out
  #   secrets:
  #     GH_APP_NAME: "my-anya-ci" # name of the GitHub App for anya
  #     DOCKER_REGISTRY: "docker.io" # docker.io
  #     DOCKER_REPO: my-organisation # organisation
  #     DOCKER_USER: my-username
  #     DOCKER_PASS: "superSecret"
  #     SLACK_CHANNEL: "CI/CD"
  #     SLACK_WEBHOOK: "https://hooks.slack.com/services/ABC/XYZ/ndfjhkfdjk"
  #     PREV_HOST: "anya.example.com"  # anya.example.com for preview deployments
  #     PREV_TLS: "anya-tls" # name of the TLS certificate for PREV_HOST
  #     PROD_HOST: example.com # root domain of the application in production
  #     PROD_PATH: "/"  # endpoint/path of your application in production
  #     PROD_TLS: "prod-tls"  # name of the TLS certificate for PROD_HOST
  #     PROD_BRANCH: master # branch name for production deployments
  #   sshKey: ""  # to pull from private repositories
  #   # sshKey: |-
  #   #  -----BEGIN RSA PRIVATE KEY-----
  #   #  IIEpAIBAAKCAg1wyZD164xNLrANjRrcsbieLwHJ6fKD3LC19E...
  #   #  ...
  #   #  ...
  #   #  -----END RSA PRIVATE KEY-----

certificate: {}
  # name:
  # crt: |
  #   -----BEGIN CERTIFICATE-----
  #   <base64>
  #   -----END CERTIFICATE-----
  # key: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #   <base64>
  #   -----END RSA PRIVATE KEY-----

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
