# Set this to true to enable Kubernetes RBAC support (recommended)
rbac:
  enabled: true

# please, do not change this values
service:
  name: brigade-github-app
  type: ClusterIP

ingress:
  # please, do not change this value
  enabled: false

# please, DO change this values
github:
  # This represents the unique ID for a GitHub App
  # The value can be retrieved from the main App page or any inbound webhook payloads
  appID: 00000
  # Trigger a Check Suite on Pull Requests
  # This will need to be set to true to enable running Check Suites on PRs originating from forks
  checkSuiteOnPR: false
  # The x509 PEM-formatted keyfile GitHub issued for your App.
  # key: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #
  #   -----END RSA PRIVATE KEY-----
