# Set this to true to enable Kubernetes RBAC support (recommended)
rbac:
  enabled: true

service:
  name: brigade-github-app
  type: ClusterIP

ingress:
  enabled: false
  # # Used to create an Ingress record.
  # hosts:
  #   - test.anya.run
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
  #   kubernetes.io/ingress.global-static-ip-name: anya-test-ip
  # tls:
  #   # Secrets must be manually created in the namespace.
  #   - secretName: anya-tls
  #     hosts:
  #     - test.anya.run

github:
  # The x509 PEM-formatted keyfile GitHub issued for you App.
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    XXX
    -----END RSA PRIVATE KEY-----
