# Set this to true to enable Kubernetes RBAC support (recommended)
rbac:
  enabled: true
api:
  enabled: true
  name: brigade-api
  # tag:
  service:
    name: brigade-api
    type: NodePort
    externalPort: 7745
    internalPort: 7745
