# Default values for anya.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 80

ingress:
  host: anya.example.com

  #annotations:
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"	# remove this, if TLS is active

  ghAppServiceName: brigade-github-app-brigade-github-app
  ghAppServicePath: /events/github
  ghAppServicePort: 80

  dashboardServiceName: kashti-kashti
  dashboardServicePath: /
  dashboardServicePort: 80

  apiServiceName: brigade-brigade-api
  apiServicePath: /v1
  apiServicePort: 7745

  tls:
    # Secrets must be manually created in the namespace.
    - secretName: anya-tls
      hosts:
      - anya.example.com

oauthProxy:
  enabled: false
  authUrl: "https://anya.example.com/oauth2/auth"
  authSignin: "https://anya.example.com/oauth2/start"

certificate: {}
  # name:
  # crt: |
  #   -----BEGIN CERTIFICATE-----
  #   <base64>
  #   -----END CERTIFICATE-----
  # key: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #   <base64>
  #   -----END RSA PRIVATE KEY-----

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
