apiVersion: v1
kind: ConfigMap
metadata:
  name: anya-brigade-pipeline
  namespace: anya
  labels:
    app.kubernetes.io/managed-by: tiller
    app.kubernetes.io/instance: anya-brigade-pipeline
    helm.sh/chart: {{ include "anya.fullname" . }}
    app.kubernetes.io/name: anya-brigade-pipeline
data:
  brigade.js: |-
{{ .Files.Get "files/brigade.js" | indent 4 }}
