{{- $fullName := include "anya.fullname" . -}}
{{- range .Values.projects }}
{{ if .secrets.DOCKER_PASS }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred-{{ sha256sum .project| trunc 54 }}
  namespace: anya
  labels:
    chart: {{ $fullName }}
    release: {{ $fullName }}
    heritage: {{ $fullName }}
  annotations:
    projectName: {{ .project | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{- printf "{\"auths\": {\"%s\": {\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\": \"%s\"}}}" .secrets.DOCKER_REGISTRY .secrets.DOCKER_USER .secrets.DOCKER_PASS .secrets.DOCKER_EMAIL (printf "%s:%s" .secrets.DOCKER_USER .secrets.DOCKER_PASS | b64enc) | b64enc | indent 1 }}
{{- end -}}
{{- end -}}
